main = ".open-next/worker.js"
name = "ilkom-forum"
compatibility_date = "2025-09-25"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
# Force production behavior in worker to avoid Next dev-only dynamic requires
NODE_ENV = "production"